### ISSUE TITLE
Panic on URL evaluation

### ISSUE THREAD

**Issue by C-Sto** [C-Sto/recursebuster#15]
Command line:
`~/go/bin/recursebuster -u http://$line -w bang.txt -k -noui -t 100 -timeout 5 -norecursion -o dirs`

```
panic: runtime error: invalid memory address or nil pointer dereferenceGET:https://domain.com/path
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x755d43]

goroutine 17920 [running]:
github.com/c-sto/recursebuster/librecursebuster.(*State).evaluateURL(0xc42016e240, 0x838b2c, 0x3, 0xc42152e0f0, 0x2f, 0xc420154870, 0x2f, 0xc4210ec000, 0x33, 0x0, ...)
        /root/go/src/github.com/c-sto/recursebuster/librecursebuster/net.go:144 +0xe3
github.com/c-sto/recursebuster/librecursebuster.(*State).testURL(0xc42016e240, 0x838b2c, 0x3, 0xc42152e0f0, 0x2f, 0xc420154870)
        /root/go/src/github.com/c-sto/recursebuster/librecursebuster/logic.go:122 +0x163
created by github.com/c-sto/recursebuster/librecursebuster.(*State).dirBust
        /root/go/src/github.com/c-sto/recursebuster/librecursebuster/logic.go:244 +0x6fc
```

**Comment by ss23** [comment]
I've also received this error. Is there a quick fix for it?

**Comment by C-Sto** [comment]
@ss23 I suspect the stacktrace has changed a bit since I posted this, do you have the error output & a rough command line? Will take a look now

**Comment by C-Sto** [comment]
For reference,  https://github.com/C-Sto/recursebuster/commit/b72a23b53073c90989467a54ce9f36a61bd572af should have fixed the above issue, but I was never able to reproduce to positively verify it resolved this issue. A quick workaround _should_ be to use the `-nospider` flag

**Comment by ss23** [comment]
I wasn't running the latest version, but I'll pull and rebuild again now.

In case it's useful, the stack trace I got was like this (I was running in GUI mode, hence the slightly broken output):
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                │
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x755ea3](pgup|pgdown) Move 10 lines                                                                                                                              │
│ctrl + (t) Add worker, (y) Remove worker                                                                                                                                                                                       │
goroutine 15 [running]:3.37.10:9201/search                                                                                                                                                                                      │
github.com/c-sto/recursebuster/librecursebuster.(*State).evaluateURL(0xc420174240, 0x839eec, 0x3, 0xc4207770a0, 0x1e, 0xc42014c7b0, 0x1e, 0xc4205625a0, 0x22, 0xc420449f60, ...)────────────────────────────────────────────────┘
	/root/go/src/github.com/c-sto/recursebuster/librecursebuster/net.go:144 +0xe3
github.com/c-sto/recursebuster/librecursebuster.(*State).testURL(0xc420174240, 0x839eec, 0x3, 0xc4207770a0, 0x1e, 0xc42014c7b0)
	/root/go/src/github.com/c-sto/recursebuster/librecursebuster/logic.go:160 +0x163
github.com/c-sto/recursebuster/librecursebuster.(*State).testWorker(0xc420174240)
	/root/go/src/github.com/c-sto/recursebuster/librecursebuster/logic.go:140 +0x72
created by github.com/c-sto/recursebuster/librecursebuster.(*State).StartManagers
	/root/go/src/github.com/c-sto/recursebuster/librecursebuster/logic.go:26 +0x12e
```

**Comment by ss23** [comment]
Latest version gives this error and stacktrace (this is from a CTF, so could be a hostile webserver, but nonetheless):

```panic: runtime error: invalid memory address or nil pointer dereference                                                                                                               │
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x755ea3]─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

goroutine 45 [running]:
github.com/c-sto/recursebuster/librecursebuster.(*State).evaluateURL(0xc4200b50e0, 0x839eec, 0x3, 0xc4204b3400, 0x1e, 0xc42008da40, 0x1e, 0xc42052e3f0, 0x22, 0xc420449f60, ...)
	/root/go/src/github.com/c-sto/recursebuster/librecursebuster/net.go:144 +0xe3
github.com/c-sto/recursebuster/librecursebuster.(*State).testURL(0xc4200b50e0, 0x839eec, 0x3, 0xc4204b3400, 0x1e, 0xc42008da40)
	/root/go/src/github.com/c-sto/recursebuster/librecursebuster/logic.go:160 +0x163
github.com/c-sto/recursebuster/librecursebuster.(*State).testWorker(0xc4200b50e0)
	/root/go/src/github.com/c-sto/recursebuster/librecursebuster/logic.go:140 +0x72
created by github.com/c-sto/recursebuster/librecursebuster.(*State).StartManagers
	/root/go/src/github.com/c-sto/recursebuster/librecursebuster/logic.go:26 +0x12e
```

**Comment by ss23** [comment]
I've confirmed this looks to be mainly an issue in the case of a badly written HTTP server. For reference, gobuster will also return an error (but not a segfault) in this case:
```
=====================================================
2018/11/18 13:07:11 Starting gobuster
=====================================================
2018/11/18 13:07:14 [!] Get http://[ctf-box]/search: net/http: HTTP/1.x transport connection broken: malformed HTTP status code "category"
```

In case you want to build a test-case or server to replicate the behavior, here is verbose cURL output (showing a non-compliant HTTP server):
```
$ curl -v http://[ctf-box]/search
*   Trying 10.13.37.10...
* TCP_NODELAY set
* Connected to [ctf-box] ([ctf-box]) port [ctf-port] (#0)
> GET /search HTTP/1.1
> Host: [ctf-box]
> User-Agent: curl/7.61.0
> Accept: */*
> 
* Connection #0 to host 10.13.37.10 left intact
Missing category
```

Hopefully this is enough to fix the issue. For behavior, it would be nice to do what gobuster does and explicitly note it down as an error (which in this case is the same as a "found" URL).

**Comment by ss23** [comment]
Whoops, I was running the old binary, not the latest version. The latest version doesn't give an error, no panics, etc, but also doesn't seem to print an error. I'd consider this issue closed, and I'll open a new issue with the above curl test-case.

**Comment by C-Sto** [comment]
Good to hear, less good to hear that you got stung by the go-not-building-proper binary problem :(

I'd like the ability to treat those incorrect responses as a finding (so they get added to the busted.txt output etc), I'll leave this issue open until _that_ has been implemented properly

**Comment by C-Sto** [comment]
Changed my mind, going to open a new issue for that feature
