### ISSUE TITLE
Segfault while running in GUI mode

### ISSUE THREAD

**Issue by ss23** [C-Sto/recursebuster#17]
While running recursebuster with most of the default options (-ext html,asp, -w, -u, -k), I recieved the following error during a run:
```
INFO: Finished dirbusting: https://[x]/
INFO: Dirbusting https://[x]/index.html/
GOOD: Found GET https://[x]/index.html/%20 [200 OK]

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71af21]

goroutine 9 [running]:
github.com/jroimartin/gocui.(*View).draw(0xc42020e2d0, 0x2518, 0xc420046d80)
        /home/ss23/go/src/github.com/jroimartin/gocui/view.go:328 +0x991
github.com/jroimartin/gocui.(*Gui).draw(0xc420f80000, 0xc42020e2d0, 0x0, 0x0)
        /home/ss23/go/src/github.com/jroimartin/gocui/gui.go:581 +0xcc
github.com/jroimartin/gocui.(*Gui).flush(0xc420f80000, 0x0, 0x0)
        /home/ss23/go/src/github.com/jroimartin/gocui/gui.go:462 +0x20e
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc420f80000, 0x0, 0x0)
        /home/ss23/go/src/github.com/jroimartin/gocui/gui.go:384 +0x224
github.com/c-sto/recursebuster/librecursebuster.(*State).StartUI(0xc420166360, 0xc420f5bab0, 0xc420072360)
        /home/ss23/go/src/github.com/c-sto/recursebuster/librecursebuster/ui.go:71 +0x4e5
created by main.main
        /home/ss23/go/src/github.com/c-sto/recursebuster/main.go:100 +0x146a
```

Could be a bug in gocui, but I thought I'd create the bug here in case it's something fixable on the recursebuster end.

This was built recently (28th of November) using the latest version of recursebuster.

**Comment by C-Sto** [comment]
I vaguely recall looking into this at the time and not having any idea what could have caused it. The code has changed a fair bit since then - I don't suppose you've run across this again have you @ss23 ?

**Comment by ss23** [comment]
Haven't had it again, happy to close. Will re-open if I see it again :)
