### ISSUE TITLE
Investigate Extension race condition

### ISSUE THREAD

**Issue by C-Sto** [C-Sto/recursebuster#3]
```
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 1 [running]:
sync.(*WaitGroup).Wait(0xc42013a1d0)
        /usr/lib/go-1.10/src/sync/waitgroup.go:131 +0xbb
main.main()
       /go/src/github.com/C-Sto/recursebuster/main.go:209 +0x17e0
```

**Comment by C-Sto** [comment]
Worked it out, it's because I'm bad at writing code and computers are hard. A lethal combination.
